### PR TITLE
Fix scaling issue on HiDPI displays

### PR DESCRIPTION
**Pull request by alexdevero**
Fixes scaling issue on HiDPI displays observed on Windows 10 with 125 % scaling factor.

Before:
rambox-before

After:
rambox-after

### CODE REVIEW

**Comment by saenzramiro** [comment]
Thank you!

**Comment by alexdevero** [comment]
@saenzramiro I'm glad i can help you. And, I hope this is only the first of my PRs.

**Comment by ericzawo** [comment]
How do I add this to my Rambox install? It's getting annoying having to re-install it every day.

**Comment by alexdevero** [comment]
@ericzawo you will have to wait until @saenzramiro releases new version of Rambox.

**Pull request merged**
