### PR TITLE
Renaming process title with hostname

### LINKED ISSUE #1267: "Rambox Helper" could it be "Rambox `<name of service>` Helper"?
activity_monitor__all_processes_

"Rambox Helper" could it be "Rambox `<name of service>` Helper"?

With many services its hard to identify which one eats the most memory and cpu.
I think ability to identify which services are slowing down whole app would be nice addition that should also help in reducing services memory and cpu hunger - since you know which ones are too hungry, you can report to their authors.

### PR DESCRIPTION
**Pull request by maxerbox**
Has been tested in Debian with gnome.
Need to be confirmed in windows & mac
Closes #1267

### CODE REVIEW

**Comment by maxerbox** [comment]
Ps: gnome-system-monitor seems a little buggy, it needs a restart to work

**Comment by pirate** [comment]
@maxerbox I tried to test this yesterday but ran into a gnarly issue on my system installing one of the Electron dev dependencies I unfortunately don't have time to fix at the moment.

If you still want some testing help, send me a dev build for macOS from this branch and I'd be happy to run it for a while and report back with any issues!

**Comment by pirate** [comment]
Bump, it would be great to have this merged, but not a huge priority. I'm still willing to test it if someone can send me a macOS build of this PR.

**Comment by Corchoneitor** [comment]
Hi. Windows update.

For starters, commits here so far don't do anything on Windows. I've been investigating this for several hours and it's seems to be a dificult (impossible?) thing to do on Windows (didn't tested it on MacOS). 

Looks like Windows does not allow us to change processes names on the way for each webview. Unfortunately, each one would take the name of the father process.

Please, someone try to acomplish this on Windows and/or MacOS and let us know!

**Comment by pirate** [comment]
sigh, bump

**Pull request closed without merging**
