### PR TITLE
Service icon loading

### PR DESCRIPTION
**Pull request by maxetime**
This is PR for #113, it is only for slack at the moment but other service can be added easily.  
Thanks to @nderscore for is workaround which I base this PR on.

### CODE REVIEW

**Comment by saenzramiro** [comment]
Thank you!

**Comment by nderscore** [comment]
Thanks for taking the time to integrate my solution into the project @maxetime and thanks for including it in the next release @saenzramiro !!! 😄

**Comment by tboerger** [comment]
Any timeline when you will publish this release?

**Comment by CombeeMike** [comment]
The new icon looks a little broken on my team:
image

Is this as intended or do we have to follow some special rules with our icon size etc.?

**Comment by nderscore** [comment]
@CombeeMike This happens when the service name field is empty. I had the same issue (#1209) and have a fix for it in an open pull request (#1210). I've posted a temporary workaround in the issue ticket.

**Pull request merged**
