### PR TITLE
Add workplace (facebook at work)

### PR DESCRIPTION
**Pull request by atao**
hello,
I add workplace in services list.
Thanks

### CODE REVIEW

**Comment by saenzramiro** [comment]
Thank you!

**Comment by atao** [comment]
Update from original project.

**Comment by Verbal-Kint-nl** [comment]
My company has enabled single sign-on. I get the following screen:
screen shot 2017-03-13 at 13 27 35
When I click Log In, I only get a white screen:
screen shot 2017-03-13 at 13 27 44
I think the website is trying to open a pop-up, that's what it does in other 'browsers'. Is it possible to incorporate this into the app?

Thanks!

**Comment by saenzramiro** [comment]
@Verbal-Kint-nl I will try to take a look for next release.

**Comment by gokhandemirhan** [comment]
Same problem here

**Pull request merged**
