### PR TITLE
Added spellcheck

### PR DESCRIPTION
**Pull request by aropop**
Hi, 
I wanted spellcheck and saw some people requesting it too, so quickly created it!

### CODE REVIEW

**Comment by saenzramiro** [comment]
Great job! Thanks!

**Comment by aropop** [comment]
Right now only works on services that use input or textareas, but many use the contenteditable attribute, will look into this.

**Comment by saenzramiro** [comment]
Any news on this?

**Comment by aropop** [comment]
Nope currently have my exam period so can't really do any updates

**Pull request merged**
