### PR TITLE
Add Google Allo Service

### PR DESCRIPTION
**Pull request by vivekkrish**
Google Allo for Web (https://allo.google.com/web) went live earlier this morning, and operates in a manner similar to WhatsApp (scan QR code).

This PR adds the Allo for Web Service to the manifest of available services in Rambox.

### CODE REVIEW

**Comment by efraimbart** [comment]
Looks like `dont_update_unread_from_title: true` is only for when you call the `setUnreadCount()` manually, it tells it not to look at the title for the count.

**Comment by efraimbart** [comment]
@vivekkrish Nice! 
Just out of curiosity, why not use the `setUnreadCount()` method?

**Comment by vivekkrish** [comment]
Hi @efraimbart, Apologies for the earlier premature comment (which I have now deleted).

As per your suggestion, my code is now using `setUnreadCount()`, and the `dont_update_unread_from_title` remains set to `true`.

**Comment by saenzramiro** [comment]
Thank you guys!

**Pull request merged**
