### PR TITLE
Added chrome extensions support

### LINKED ISSUE #2624: Support for chrome extensions
Lots of messaging services (like gmail) needs some extensions to be really usable in a daily base.

It could be great to add the support for chrome extensions.

There was an old issue about this (#732) but it has been closed for being stale.

It seems that electron now allow to add extensions, but it needs some modifications in Rambox's code. (see https://github.com/ramboxapp/community-edition/issues/732#issuecomment-491538429)

Here is the documentation about electron's support of extensions : https://www.electronjs.org/docs/api/browser-window#browserwindowaddextensionpath

### PR DESCRIPTION
**Pull request by EmrysMyrddin**
This is a first attempt to add chrome extension support.
It is very basic, it just opens the possibility for the user to add path of extensions wanted.

Perhaps it will be possible to make a more fancy version of this, but I think it is a good first step :-)

Closes #2624.

### CODE REVIEW

**Comment by EmrysMyrddin** [comment]
This is adding a warning at startup for every extension loaded. It is bug from electron, probably fixed in newer versions.

**Review by cscuderi — APPROVED** [review]
LGTM!

**Comment by Vioner** [comment]
LGTM too :) 
I've tried integrating custom made and standard [darkreader](https://github.com/darkreader/darkreader) extension, but achieved no success :( 

I'll try to replicate [Ferdi's Darkreader implementation](https://github.com/getferdi/ferdi/commit/1eb148d121dbcbe1e54085a9fb897fe7ac1529b7) someday this or next month. 

If any of you tried integrating DarkReader, let me know.

**Comment by aboimpinto** [comment]
I'm using Grammarly and this is the extension that I would like to see it work

**Comment by Vioner** [comment]
Actually, I've already implemented darkreader using the npm module - PR: https://github.com/ramboxapp/community-edition/pull/2823
As for other extensions - I'll look into that later this or next month as well.

**Comment by EmrysMyrddin** [comment]
@aboimpinto Grammarly should work with this PR, if you have the occasion to test it, it was one of my goals with this PR :-)

I will make another PR when this one will be merged to add the possibility to open settings page of each configured extensions. The next step will be to allow to trigger the `extension button` on a tab.

**Comment by aboimpinto** [comment]
@EmrysMyrddin I will ... when we will have this feature on a release?
is this already on the 0.7.6 version?

**Comment by Yak86** [comment]
Any updates on whether this would be merged to the release version? Wasn't able to get it working on the forked version. Chrome extensions are pretty key in making Rambox fuller featured.

**Comment by EmrysMyrddin** [comment]
@Yak86 What do you mean ? You have tested my PR and it doesn't work ?

I'm waiting from the maintainers to have a review or something... I don't why this PR is stuck.

**Review by joelemanoel — APPROVED** [review]

**Pull request closed without merging**
