### PR TITLE
Change teamwork Chat URL template

### PR DESCRIPTION
**Pull request by luukschakenraad**

### CODE REVIEW

**Comment by saenzramiro** [comment]
Hello @luukschakenraad,

Can you explain why you suggest changing the URL? Is Teamwork also self-hosted service?

**Comment by luukschakenraad** [comment]
Hi @saenzramiro 

You cannot host teamwork yourself, but you can assign your company-URL to it. e.g.: teamwork.companyname.com. See my ticket about it: https://github.com/saenzramiro/rambox/issues/1404

**Comment by saenzramiro** [comment]
So if I understand correctly, you can configure a CNAME record in your DNS server to point to the Teamwork server?

**Comment by luukschakenraad** [comment]
That's correct: http://support.teamwork.com/projects/general-settings/using-a-custom-domain-name

**Pull request merged**
