### PR TITLE
Integrate Darkreader for global dark theme support - both UI and Service tabs

### LINKED ISSUE #1532: Dark mode & Small mode settings
1) Would be nice if we had a setting to make the header bar smaller (less height) with the icons having less padding.

2) Would be nice to have a setting to make the header dark

I have a pretty hacky way of getting this for myself already (`CTRL+SHIFT+I` and paste to console), but it's a bit tedious to run every time Rambox is restarted.

```JavaScript
// smaller tabs
document.querySelector('.x-tab-bar').style.maxHeight="41px";
document.querySelector('.x-panel-body').style.top="41px";
document.querySelectorAll('.x-tab').forEach(function(el){el.style.padding='4px';});

// dark mode
document.querySelector('.x-tab-bar').style.backgroundColor='#20272D';
document.querySelectorAll('.x-tab').forEach(function(el){el.style.backgroundColor='#40474D';});

// trigger recalculation of styles via tab switch 
let current = document.querySelector('.x-tab-active');
current.previousSibling.click();
current.nextSibling.click();
current.click();
```

I would love for a way to store custom scripts/css in for the whole app OR have checkboxes to achieve dark mode and smaller header.

### PR DESCRIPTION
**Pull request by Neurovert**
Screen Capture_select-area_20200912225856

Fixes #107 
Fixes #1532 

Added:
- [x]  Preferences window - checkbox enabling Rambox dark mode:
- [x] Rambox UI is darkified with [Darkreader](https://github.com/darkreader/darkreader) 
- [x] All service tabs are also darkified, but for now, toggling dark mode needs you to relaunch the app or reload service tab
- [x] Of course setting is remembered each session
- [x] Dark mode is enabled by default! 

For future releases:
- [ ] add instant update of service tabs when dark mode toggled (now they need to be reloaded)
- [ ] toggle global dark mode with a hotkey
- [ ] toggle per service (now it's global)
- [ ] hotkey for `toggle dark theme - current tab`
- [ ] toggle from the top, hideable menu bar or from the services row
- [ ] add the config popup for Darkreader customization like in Chrome

### CODE REVIEW

**Comment by Vioner** [comment]
@fvulich @saenzramiro 
Please check my PR and possibly merge it. 
It's been 3 months. I've been using my version all this time and had no problems.

Only thing that might need to be changed is setting darkmode as disabled by default. 
My changes set is as enabled by default.

**Comment by saenzramiro** [comment]
@Vioner thank you! We will be reviewing and testing this feature.

**Comment by edwinclement08** [comment]
Hey, is this gonna be merged anytime soon?

**Comment by Vioner** [comment]
True, it's been 8,5 months :D

**Comment by Vioner** [comment]
@saenzramiro

**Comment by arnonuem** [comment]
woohooo

**Pull request closed without merging**
