### PR TITLE
Feature/add context menu

### PR DESCRIPTION
**Pull request by irrenhaus**
This adds an basic context menu using https://github.com/sindresorhus/electron-context-menu

Basic functionality should include Cut/Copy/Paste for text, Save Image for images, Copy Link for links and (in debug mode) Inspect Item.

### CODE REVIEW

**Comment by irrenhaus** [comment]
Is this wanted or should I close it? Just asking if I need to care about holding it up to date with the master branch.

**Comment by saenzramiro** [comment]
Thank you for your code.

Before I tested that library to add context menu but for me it didn't work ok. If I remember, it didn't work ok in Rambox tab and/or in any service. Can you check this?

**Comment by theunsfvo** [comment]
It is needed in everyday mail operations, please.

**Comment by irrenhaus** [comment]
I'll re-check soon :+1:

**Comment by YesThatAllen** [comment]
I came to Github to open an issue/feature request for this. So nice to see a PR already here.

**Comment by irrenhaus** [comment]
So, TBH, I'm having a hard time trying to compile & run current versions of Rambox.
After installing all of the dependencies including sencha & ruby, I'm still stuck with the locally built version (based on 0.4.4 release) is not working because of the error
Uncaught TypeError: Ext.cq1 is not a function
in
Services.js:24
which prevents any service window from opening.

So far I can confirm that the context menu is working in the main Rambox window, sadly I cannot even test the services I personally have accounts for because of this error.

Since I'm missing the time for trying to dig deeper into this I'll have to ask someone else to verify if this is working in the service windows.

**Comment by saenzramiro** [comment]
@irrenhaus No, it not working. When I was trying to add this feature in a previous version, I realized that works on Rambox window, but not inside services.

**Comment by orschiro** [comment]
Dear all, 

Do we have news for this?

Not having a context menu to copy links in the email programs is a big obstacle. 

Yours,

Robert

**Comment by simoniz0r** [comment]
Right click would be really nice to have when using Discord, email apps, etc.  I am really missing my right click when using Rambox!

**Comment by simoniz0r** [comment]
Please add this!  I have stopped using Rambox because it is far too annoying to not be able to right click in services such as Discord.  I really, really like Rambox, but not having access to right click is really killing my ability to use it and be sane at the same time.

**Comment by diegomachadosoares** [comment]
+1
It is really a key feature.
Glad to see that a PR is already submitted...

**Comment by NNois** [comment]
Hi,
I'm having some more problems with that copy/paste missing
we actually can't spellcheck in email...

**Comment by flying-sheep** [comment]
hey @irrenhaus, you maybe forgot the env.js.

you can rip out a working one from a binary release tarball, e.g.:

```js
wget https://github.com/saenzramiro/rambox/releases/download/0.5.3/Rambox-0.5.3-x64.tar.gz
tar xOf "Rambox-0.5.3-x64.tar.gz" "Rambox-0.5.3/resources/app.asar" >app.asar
asar ef app.asar env.js
```

**Comment by nmat** [comment]
In my opinion this should be for the 0.6.0 release and not for 1.0.0 and improve the context menu (if needed for 1.0.0) instead. Its a rather big key feature for most services.

**Comment by eloyleonardo** [comment]
+1

**Comment by davidmoore-io** [comment]
+1 on this. It's become a proper issue for me, and I think it's pretty key to the core functionality of Rambox.

**Comment by Shmasya** [comment]
Where .. why .. why it's not inlcude in last update again. Pls include this!

**Comment by simoniz0r** [comment]
Holy crap why? lol
I've honestly like forgotten Rambox was even a thing by now because it was pretty much unusable for me due to missing the context menu...

**Comment by epeli** [comment]
I don't think this has changed

> @irrenhaus No, is not working. When I was trying to add this feature in a previous version, I realized that works on Rambox window, but not inside services.

If I understand correctly the context menu works only on the Rambox tabbar not inside the services you are actually using. So this is not actually very usefull yet.

**Comment by Ash258** [comment]
Implemented in #1074

**Pull request closed without merging**
