### PR TITLE
Fixed the screenshare capability

### PR DESCRIPTION
**Pull request by cemanuelio**
This fix allow users to share their screens with apps that have this feature.

Fixes: #3083
Fixes: #2979
Fixes: #2842
Fixes: #2660
Fixes: #2655

### CODE REVIEW

**Comment by riedel** [comment]
Any news on this? Does anyone have a windows binary with this one merged? (Too lazy to build myself)

**Comment by ssbarnea** [comment]
That looks really promising but the fact that this PR did not get any attention in almost 6 months worries me.

**Comment by beltrame** [comment]
Still no love for this PR?

**Comment by riedel** [comment]
At least I can confirm that this PR really works (been using it extensively over a few weeks). 

If would feel more comfortable building this sencha stuff I would release a forked binary release as a last resort.

**Comment by beltrame** [comment]
@saenzramiro any interest?

**Comment by isabellerichard** [comment]
Hi, it seems that this PR solves the screen sharing for Teams.
Could you please merge it?

**Comment by ssbarnea** [comment]
I guess we may face the 1st birthday celebration before getting any official review of this PR... :(

**Comment by saenzramiro** [comment]
Sorry for the delay guys, thank you for this PR.

**Comment by ssbarnea** [comment]
Even later is better than never, especially as Ferni developer went rogue.

**Comment by shanness** [comment]
Damn, I gave up yesterday and swapped to Ferdi (which works for this and love the todo feature), but yeah, them shutting down their github issues is a worry..  Will keep this in mind if things go downhill.  Thanks for merging it.

**Comment by ssbarnea** [comment]
TBH, I am really disappointed about everything is happening in the boxed-browser arena. No pure open-source project, all even unstable due to being driven by a sole person or aiming to become commercial using heavy tactics and crippling the free part of the product.

Upgrade to Rambox 2 was no joy as it required me to login and after that I got a message that my 30 days trial for premium started. Nobody asked me that this would be implied, I never wanted to test any premium features and there is no option to downgrade the product to the basic one. It reminds me of what Frank did, and likely what caused creation of Ferni.

To be honest, I would likely donate using github sponsors to a such project to keep it going but I am not willing to invest in building another business around it as I do know that sooner or later I become the product. It might look like paranoia, but looking back... it might also be only past experience.

I work as an open-source developer part of Ansible team and I did not see RedHat asking/forcing someone that installed ansible to upgrade to AAP (commercial offering). The products are still free to use to everyone. In fact the free versions are always newer than the commercial ones as that is where all the changes land first.

**Pull request merged**
