### PR TITLE
Add FastMail, Hibox, CiscoSpark and Jandi services

### PR DESCRIPTION
**Pull request by TriiNoxYs**
Hi, I just added FastMail service because it was asked by @dogancelik on Gitter.
Also see #637 to add it on the site :)

### CODE REVIEW

**Comment by dogancelik** [comment]
Thanks also, clicking a link in a mail opens a blank page,

Here's the log:

```json
{
  "name": "TypeError",
  "message": "Cannot create property 'href' on string 'about:blank'",
  "stack": "TypeError: Cannot create property 'href' on string 'about:blank'\n    at Function.openExternal (/static/ajaxui/desktop/O-adf0a330.js:2:18978)\n    at eval [as _onClick] (/static/ajaxui/desktop/mail-41803f4f.js:4:6479)\n    at fire (/static/ajaxui/desktop/O-adf0a330.js:1:20847)\n    at Object.eval (/static/ajaxui/desktop/O-adf0a330.js:4:20844)\n    at Object.invoke (/static/ajaxui/desktop/O-adf0a330.js:1:23895)\n    at Object.eval [as handleEvent] (/static/ajaxui/desktop/O-adf0a330.js:1:25416)\n    at init.eval (/static/ajaxui/desktop/O-adf0a330.js:4:19920)\n    at Object.invoke (/static/ajaxui/desktop/O-adf0a330.js:1:23895)\n    at init.eval [as handleEvent] (/static/ajaxui/desktop/O-adf0a330.js:1:25416)",
  "ua": "Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Rambox/0.5.3 Chrome/53.0.2785.143 Electron/1.4.15 Safari/537.36",
  "url": "https://www.fastmail.com/mail/Inbox/REDUCTED",
  "user": "REDUCTED",
  "version": "37809a74"
}
```

**Comment by TriiNoxYs** [comment]
I also added Hibox, Cisco Spark and Jandi services.

**Comment by saenzramiro** [comment]
Thank you @TriiNoxYs ! 👏

**Comment by k1sul1** [comment]
This doesn't work for me. It builds just fine, but when I click external links in the newly created FastMail service, absolutely nothing happens.

When I add FastMail as a custom service and click and external link, I get a blank window going nowhere: 

image

**Comment by mdbraber** [comment]
This is probably due to the way Fastmail handles its external links. I don't run Fastmail in Rambox, but in a separate Fluid browser. I've worked around the open function by using the following:

```
function init() {
O.WindowController.openExternal = function(i){console.log(i);window.location.href=(i);}
}

// there is no good domloaded support in Fluid so we need a timer until ready
var _timer = setInterval(function() {
  if (/loaded|complete/.test(document.readyState)) {
    init(); // call the onload handler
  }
}, 500);
```

**Comment by dogancelik** [comment]
Thanks for the code above, that opens links inside the tab so here's the code for opening in default browser:

```js
setTimeout(function () { O.WindowController.openExternal = (i)=> {
var a = document.createElement('a');
a.href=i;
a.setAttribute('target', '_blank');
a.click();
}; }, 5000)
```

**Comment by Aktariel** [comment]
I can confirm that dogancelik's code works for me. Seems like all Rambox needs to add to "officially" support FastMail as a service.

Thanks!

**Comment by saenzramiro** [comment]
Works like a charm! Thanks guys!

**Comment by igalic** [comment]
hrm… doesn't seem to work (for me)

external links are just opened in Rambox

**Comment by igalic** [comment]
we'd still need a sensible way to open attachments… these start with `https://www.fastmail.com/unsafecontent/mail-attachment/`

**Pull request merged**
