### PR TITLE
Added a new feature: Integrated external windows !

### PR DESCRIPTION
**Pull request by maxerbox**
In order to integrate new windows (when you click on a link, it's opened in a new window), I've added a new feature that allow Rambox to integrate the new window inside Rambox in a new tab.
## Why ?

Because on slack, when you click on "Manage my server", it opens a new window.

## Quick example:
img
I'm hitting Ctr+Click to open the discord server in a new window. The link is loaded inside rambox with the current partition, it means that you are still logged !
Also, I'm hitting DEL to remove the temporary tab

I've added a new option called "Authorize window integration" which enable or disable this feature for a tab.

## Enabling this feature for a service:

In ServiceList.js, add the property `external_tab_match` for a service
Ex: `external_tab_match: 'https?:\/\/.*\.slack\.com'`

## New properties added for a ServiceList

(all default to '')

| Property Name | Type | Desc |  |  |
|------------------------|-----------------|------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|---|---|
| external_tab_match | String (regexp) | This is a string representating a regular expression (g & i flags are used) It is used to test if the new window should be opened inside rambox or not (only http & https protocols are supported). It basically match the url, and if the url is matched, it is opened |  |  |
| external_tab_not_match | String (regexp) | This is a string representating a regular expression (g & i flags  are used) It is used to test if the new window should be not opened inside rambox. It basically match the url, and if the url is matched, it will not open the tab inside rambox (even if external_tab_match match the url) |  |  |

### CODE REVIEW

**Comment by jizusun** [comment]
This feature is so cool :rocket: 
Hope to see it to be merge soon !

**Comment by saenzramiro** [comment]
Nice! 👏 
But what happens when the user has already tabs at the right or the tabbar full?

I think we should think another way to display the tabs of the opened windows... 🤔

**Comment by maxerbox** [comment]
Yeah maybe !
I was thinking about displaying only the icon, or making a tab separator.
Actually, integrated windows are always added to the right, as the last tab.
New service are added behind them properly, if you don't move them.
If there are too much tabs, you have to scroll to display them.

Take a look at this gif:
Img

**Comment by saenzramiro** [comment]
@fvulich I think we should test this and try to add this feature in next release.
@maxerbox You are awesome!

**Review by saenzramiro — COMMENTED** [review]
I was thinking that maybe we can add a new small tabbar where we open all links (with target _blank) that user clicks. Besides that, if the user Ctrl + Click, we force to open it in the default browser.

@maxerbox What do you think?

**Comment by mike391** [comment]
Will things like whatsapp open links in a tab as well? One might want these to open inside an actual browser.  This feature looks cool, but we should at least make this behaviour optional.

**Comment by maxerbox** [comment]
It is optional

**Comment by ArthurHNL** [comment]
Maybe it is possible to introduce a mode where it will open in a new tab as long as the link is from the same domain. This would come in handy when for example using outlook web app ( #2258 ) where the calendar would open in a tab but links in emails (pointing to different domains) would still open in a browser.

**Comment by Corchoneitor** [comment]
Hi guys.

What's the state of this? Did anyone else try it?

There's an obvious demand for this awesome feature... and I think we need to merge this to master ASAP.

**Comment by StraggleCraft** [comment]
Wanted to see what the status of this was, I still have to hold shift when switching orgs in msft teams.

**Comment by maxerbox** [comment]
> Maybe it is possible to introduce a mode where it will open in a new tab as long as the link is from the same domain. This would come in handy when for example using outlook web app ( #2258 ) where the calendar would open in a tab but links in emails (pointing to different domains) would still open in a browser.

That's how it works actually

**Comment by Mte90** [comment]
just a ping

**Comment by kbni** [comment]
This feature would be amazing. Shift just recently added a similar feature and the implementation is very user-friendly.

**Comment by H8to** [comment]
Hi, any news on this issue?

Thanks in advance!

Just as a temporary workaround:
https://github.com/ramboxapp/community-edition/issues/2328#issuecomment-508451591 

Notice this will cause immense CPU load if there is any "login redirection" happening? xD

**Pull request closed without merging**
